### ISSUE TITLE
TypeError: Parameter "url" must be a string, not object

### ISSUE THREAD

**Issue by kamraanki** [IBM-Blockchain/cp-web#37]
I run updated cp-web demo with instructions mentioned in read me section. It's giving following error:-

url.js:79
    throw new TypeError('Parameter "url" must be a string, not ' + typeof url);
    ^

TypeError: Parameter "url" must be a string, not object
    at Url.parse (url.js:79:11)
    at Object.urlParse [as parse](url.js:73:5)
    at parseUrl (/home/vagrant/ankit/temp/cp-web/node_modules/hfc/lib/hfc.js:2101:26)
    at new Endpoint (/home/vagrant/ankit/temp/cp-web/node_modules/hfc/lib/hfc.js:1739:20)
    at new MemberServicesImpl (/home/vagrant/ankit/temp/cp-web/node_modules/hfc/lib/hfc.js:1767:18)
    at newMemberServices (/home/vagrant/ankit/temp/cp-web/node_modules/hfc/lib/hfc.js:2032:12)
    at Chain.setMemberServicesUrl (/home/vagrant/ankit/temp/cp-web/node_modules/hfc/lib/hfc.js:285:32)
    at configure_network (/home/vagrant/ankit/temp/cp-web/app.js:238:15)
    at Object.<anonymous> (/home/vagrant/ankit/temp/cp-web/app.js:229:1)
    at Module._compile (module.js:541:32)

**Comment by masterDev1985** [comment]
The line that it is complaining about is here:
https://github.com/IBM-Blockchain/cp-web/blob/master/app.js#L238

If you add `console.log(caURL)` on the line before this one, what do you see?  It looks like something other than a string is being passed in to the MembershipServices function.

**Comment by dhyey20** [comment]
Closed due to inactivity.
