### ISSUE TITLE
Failed to deploy chaincode: EventTransactionError

### ISSUE THREAD

**Issue by kylelorenz** [IBM-Blockchain/cp-web#56]
When trying to connect my local copy of cp-web (master) to new bluemix blockchain instance running v.6 I get the following error while running gulp command.  Please advise.  Thanks,
```
...
...
chain_setup.js Successfully enrolled registrar
chain_setup.js using registrar to deploy chaincode
chain_setup.js Deploying commercial paper chaincode as: WebAppAdmin
chain_setup.js Deployment request: {"fcn":"init","args":["a","100"],"chaincodePa
th":"chaincode/","certificatePath":"/certs/peer/cert.pem"}
chain_setup.js Failed to deploy chaincode: EventTransactionError {
  error: [Error: Error creating deployment archive [/tmp/deployment-package.tar.
gz]: Error: Error on fs.createWriteStream],
  msg: 'Error: Error creating deployment archive [/tmp/deployment-package.tar.gz
]: Error: Error on fs.createWriteStream' }
chain_setup.js chaincode deployment failed: undefined
app.js: Chain setup failed: EventTransactionError {
  error: [Error: Error creating deployment archive [/tmp/deployment-package.tar.
gz]: Error: Error on fs.createWriteStream],
  msg: 'Error: Error creating deployment archive [/tmp/deployment-package.tar.gz
]: Error: Error on fs.createWriteStream' }
```

**Comment by masterDev1985** [comment]
Does the `/tmp` directory exist on your filesystem?  If you're on Windows, you'll want to make sure a `C:\tmp` directory exists.  Let me know if this works for you, @kylelorenz.

**Comment by masterDev1985** [comment]
Just deleted `C:\tmp` on my machine, got this output:

```
chain_setup.js Deployment request: {"fcn":"init","args":["a","100"],"chaincodePath":"chaincode/","certificatePath":"/certs/peer/cert.pem"}
chain_setup.js Failed to deploy chaincode: EventTransactionError {
  error:
   Error: Error creating deployment archive [/tmp/deployment-package.tar.gz]: Error: Error on fs.createWriteStream
       at Error (native)
       at C:\Users\IBM_ADMIN\Documents\obc\git\demos\cp-web\node_modules\hfc\lib\hfc.js:1411:31
       at WriteStream.<anonymous> (C:\Users\IBM_ADMIN\Documents\obc\git\demos\cp-web\node_modules\hfc\lib\sdk_util.js:163:16)
       at emitOne (events.js:101:20)
       at WriteStream.emit (events.js:188:7)
       at WriteStream.<anonymous> (fs.js:2109:12)
       at FSReqWrap.oncomplete (fs.js:123:15),
  msg: 'Error: Error creating deployment archive [/tmp/deployment-package.tar.gz]: Error: Error on fs.createWriteStream' }
chain_setup.js chaincode deployment failed: undefined
app.js: Chain setup failed: EventTransactionError {
  error:
   Error: Error creating deployment archive [/tmp/deployment-package.tar.gz]: Error: Error on fs.createWriteStream
       at Error (native)
       at C:\Users\IBM_ADMIN\Documents\obc\git\demos\cp-web\node_modules\hfc\lib\hfc.js:1411:31
       at WriteStream.<anonymous> (C:\Users\IBM_ADMIN\Documents\obc\git\demos\cp-web\node_modules\hfc\lib\sdk_util.js:163:16)
       at emitOne (events.js:101:20)
       at WriteStream.emit (events.js:188:7)
       at WriteStream.<anonymous> (fs.js:2109:12)
       at FSReqWrap.oncomplete (fs.js:123:15),
  msg: 'Error: Error creating deployment archive [/tmp/deployment-package.tar.gz]: Error: Error on fs.createWriteStream' }

C:\Users\IBM_ADMIN\Documents\obc\git\demos\cp-web\app.js:229
            throw error;
            ^
[object Object]
```

**Comment by masterDev1985** [comment]
I'll leave this open until I've pushed a note in the documentation for this.

**Comment by kylelorenz** [comment]
Adding the C:\tmp directory resolved the issue.  Thanks!
