### ISSUE TITLE
Failed to run demo using local network, Error: failed to enroll registrar: Identity or token does not match

### ISSUE THREAD

**Issue by forgeRW** [IBM-Blockchain/cp-web#67]
I set up a network with 4 peers and a CA as described here (https://github.com/IBM-Blockchain/cp-web/blob/master/docs/use_local_hyperledger.md). I verified that the network is running by checking all 4 HTTP chain network endpoints, which gave responses similar to the one in the link above, i.e. the responses all containws "height": 1
  Next, I followed "Option 2: Use a locally hosted Hyperledger Network (such as one from docker-compose)" under Getting Started section. I'm using Docker for Mac for the peers and CA. I did try running the demo again from scratch, i.e. removing all docker containers and images, removing cp-web, running docker-compose with four-peer-ca.yaml, cloning cp-web, running npm install and gulp. I still got the same error message.
  Would anyone know how to resolve this error? Any tips are appreciated.

mycreds.json is given below:
{
  "credentials": {
    "peers": [
      {
        "discovery_host": "localhost",
        "discovery_port": "7051",
        "api_host": "localhost",
        "api_port": 7051,
        "type": "peer",
        "id": "vp0"
      },
      {
        "discovery_host": "localhost",
        "discovery_port": "8051",
        "api_host": "localhost",
        "api_port": 8051,
        "type": "peer",
        "id": "vp1"
      },
      {
        "discovery_host": "localhost",
        "discovery_port": "9051",
        "api_host": "localhost",
        "api_port": 9051,
        "type": "peer",
        "id": "vp2"
      },
      {
        "discovery_host": "localhost",
        "discovery_port": "10051",
        "api_host": "localhost",
        "api_port": 10051,
        "type": "peer",
        "id": "vp3"
      }
    ],
    "ca": {
      "sub-ca": {
        "url": "localhost:7054",
        "discovery_host": "localhost",
        "discovery_port": "7054",
        "api_host": "localhost",
        "api_port": 7054,
        "type": "ca",
        "newUsersObj": [
          {
            "enrollId": "WebAppAdmin",
            "enrollSecret": "DJY27pEnl16d",
            "group": "1",
            "affiliation": "institution_a",
            "username": "WebAppAdmin",
            "secret": "DJY27pEnl16d"
          }
        ]
      }
    },
    "users": [
      {
        "username": "WebAppAdmin",
        "secret": "DJY27pEnl16d",
        "enrollId": "WebAppAdmin",
        "enrollSecret": "DJY27pEnl16d"
      }
    ],
    "cert": "https://blockchain-certs.mybluemix.net/us.blockchain.ibm.com.cert"
  }
}

I get the error message below:
chain_setup.js Getting registrar: WebAppAdmin
app.js: Server Up - localhost:3000
chain_setup.js successfully got registrar. Enrolling with secret: DJY27pEnl16d
  hfc Enrolling [req={"enrollmentID":"WebAppAdmin","enrollmentSecret":"DJY27pEnl16d"}] +0ms
  hfc [MemberServicesImpl.enroll] [{"enrollmentID":"WebAppAdmin","enrollmentSecret":"DJY27pEnl16d"}] +1ms
  hfc [MemberServicesImpl.enroll] Generating keys... +1ms
  hfc [MemberServicesImpl.enroll] Generating keys...done! +75ms
  hfc [MemberServicesImpl.enroll] Generating request! "3059301306072a8648ce3d020106082a8648ce3d0301070342000403d765a50d9dc684b9ad43c7e817ca1150fb6a493c8290fe1fa2daf45322f56034b1fa668bdf8db89856421620ec230e3e1d44036f11cdf860385aff22aae812" +3ms
  hfc [MemberServicesImpl.enroll] Adding signing key! +0ms
  hfc [MemberServicesImpl.enroll] Assding encryption key! +0ms
  hfc [MemberServicesImpl.enroll] [Contact ECA] {"ts":{"seconds":{"low":1483896021,"high":0,"unsigned":false},"nanos":0},"id":{"id":"WebAppAdmin"},"tok":{"tok":{"buffer":{"type":"Buffer","data":[68,74,89,50,55,112,69,110,108,49,54,100]},"offset":0,"markedOffset":-1,"limit":12,"littleEndian":false,"noAssert":false}},"sign":{"type":0,"key":{"buffer":{"type":"Buffer","data":[48,89,48,19,6,7,42,134,72,206,61,2,1,6,8,42,134,72,206,61,3,1,7,3,66,0,4,3,215,101,165,13,157,198,132,185,173,67,199,232,23,202,17,80,251,106,73,60,130,144,254,31,162,218,244,83,34,245,96,52,177,250,102,139,223,141,184,152,86,66,22,32,236,35,14,62,29,68,3,111,17,205,248,96,56,90,255,34,170,232,18]},"offset":0,"markedOffset":-1,"limit":91,"littleEndian":false,"noAssert":false}},"enc":{"type":0,"key":{"buffer":{"type":"Buffer","data":[48,89,48,19,6,7,42,134,72,206,61,2,1,6,8,42,134,72,206,61,3,1,7,3,66,0,4,145,54,229,125,14,44,169,0,109,25,222,136,169,170,154,235,250,194,31,195,117,147,197,201,51,108,174,232,176,6,131,175,229,166,88,152,115,96,76,190,70,83,244,53,110,181,199,22,64,145,214,236,48,247,32,103,218,39,31,5,229,60,252,201]},"offset":0,"markedOffset":-1,"limit":91,"littleEndian":false,"noAssert":false}},"sig":null}  +0ms
  hfc [MemberServicesImpl.enroll] failed to create cert pair: err={"code":2,"metadata":{"_internal_repr":{}}} +9ms
  hfc [memberServices.enroll] err=Error: Identity or token does not match., enrollment=undefined +0ms
chain_setup.js failed to enroll registrar: Identity or token does not match.
chain_setup.js couldn't configure the network
app.js: Chain setup failed: { Error: Identity or token does not match.
    at /.../cp-web/node_modules/grpc/src/node/src/client.js:417:17 code: 2, metadata: Metadata { _internal_repr: {} } }
/.../cp-web/app.js:225
            throw error;
            ^

Error: Identity or token does not match.
    at /.../cp-web/node_modules/grpc/src/node/src/client.js:417:17

**Comment by marcoess** [comment]
Did you solve the problem? I got the same one ..

**Comment by gcoon151** [comment]
I was helping someone with this this weekend. It seems the first time it deploys fine, but on any change and redeploy it has the wrong mycreds.json information or is not reading the environment details correctly. Reproduction steps: deploy sample app with the deploy to bluemix. Works fine. Make any modifiction to the app and redeploy, get this error.
